### ISSUE TITLE
how to build and package jar file in intellij idea

### ISSUE THREAD

**Issue by gaoxuesong** [hdinsight/hdinsight-spark-examples#1]
Hi, I want to know how to build and package jar file in Intellij idea?
And would I using HDInsight Spark ( preview ) to run the jar file?
Thanks.

**Comment by shanyu** [comment]
This example project use maven for build. You can use command line (see build.cmd as an example) to build and package the jar file.

You can certainly use intellij for development. In the UI, you can import the maven project by pointing to the folder that contains the "pom.xml".
